### ISSUE TITLE
CircleCI workflow

### ISSUE THREAD

**Issue by Malmsteg** [NETGruppEn/Project_Ragnarok#35]
/.circleci/config.yml

```yml
    jobs:
      - node/test:
          filters:
            branches:
              only: 
                - develop
```

shoulde be changed to

```yml
    jobs:
      - node/test:
          filters:
            branches:           
              only:
              - staging
              - main
```
